- name: NDSLabs| copy yaml
  template: src="{{ item }}.j2" dest="/tmp/{{ item }}"
  with_items:
    - ndslabs-configmap.yaml
    - ndslabs-smtp.yaml
    - ndslabs-ingress.yaml
    - ndslabs-etcd.yaml
    - ndslabs-apiserver.yaml
    - ndslabs-webui.yaml

- name: NDSLabs| create configmap
  command: /opt/bin/kubectl apply -f "/tmp/ndslabs-configmap.yaml"

- name: NDSLabs| create smtp service
  command: /opt/bin/kubectl apply -f "/tmp/ndslabs-smtp.yaml"

- name: Ingress status
  command: /opt/bin/kubectl get ing ndslabs-ingress
  register: ingress
  failed_when: ingress.rc < 0

- name: NDSLabs| create ndslabs-ingress
  command: /opt/bin/kubectl create -f "/tmp/ndslabs-ingress.yaml"
  when: ingress.rc != 0

- name: NDSLabs| create ndslabs-etcd
  command: /opt/bin/kubectl apply -f "/tmp/ndslabs-etcd.yaml"

- name: NDSLabs| create ndslabs-apiserver
  command: /opt/bin/kubectl apply -f "/tmp/ndslabs-apiserver.yaml"

- name: NDSLabs| create ndslabs-webui
  command: /opt/bin/kubectl apply -f "/tmp/ndslabs-webui.yaml"
