---

# Provision an OpenStack volume for this instance's extra storage
- name: OpenStack storage volume
  become: false
  connection: local
  os_volume:
    state: present
    wait: yes
    size: "{{ storage_volume_gb }}"
    display_name: "{{ ansible_host }}-storage-volume"
  register: storagevol

# Attach the OpenStack volume to the instance
- name: Attach OS volume
  connection: local
  become: false
  os_server_volume:
    state: present
    wait: yes
    server: "{{ ansible_host }}"
    volume: "{{ ansible_host }}-storage-volume"
  register: storage_vol_attach
  when: storagevol.changed

# Save storage volume path from /dev
- set_fact:  storage_volume_dev="{{ storage_vol_attach.attachments[0].device }}"
  when: storagevol.changed

# Format storage volume with ext4
- name: Format storage volume
  become: true
  filesystem: fstype=ext4 dev="{{ storage_volume_dev }}"
  when: storagevol.changed

# Create systemd entries for XFS storage mount
- name: create storage volume mount service for systemd
  become: true
  template: src=ext4-mount.service.j2 dest="/etc/systemd/system/media-storage.mount"
  when: storagevol.changed
  
# Specify XFS mount to startup with the node
- name: start storage volume mount service and set to start on startup
  become: true
  service: name="media-storage.mount" state=started enabled=yes
  when: storagevol.changed
