---

- name: Set Update Strategy
  become: true
  lineinfile: dest=/etc/coreos/update.conf line="REBOOT_STRATEGY=off"

- name: Do not update CoreOS
  become: true
  systemd: name=update-engine state=stopped masked=yes

- name: CoreOS no locksmithd
  become: true
  systemd: name=locksmithd state=stopped masked=yes

- name: Update MTU
  become: true
  template: src=10-net.rules.j2 dest=/etc/udev/rules.d/10-net.rules

- name: notify systemd of MTU change
  become: true
  command: systemctl restart systemd-udev-trigger.service

- name: fix coreos docker BIP and MTU - make service dir
  become: true
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: fix coreos BIP and MTU - copy the service file
  become: true
  template: src=10-docker0.conf.j2 dest=/etc/systemd/system/docker.service.d/10-docker0.conf

- name: Get CoreOS version
  shell: "(. /etc/os-release && echo ${VERSION}) | cut -d. -f1"
  register: os_version

- name: Check CoreOS version
  assert:
    that:
      - "{{ os_version.stdout }} > 1097"
    msg:  "FATAL:  CoreOS version lacks rpc.quotad"

- name: Fix hosts file
  become: true
  lineinfile: state=present create=yes dest="/etc/hosts" line="127.0.0.1 localhost"

- name: CoreOS set our timezone
  become: true
  command:  timedatectl set-timezone America/Chicago
